#!/usr/bin/ash

build() {
	add_runscript
	add_all_modules '/netfilter/nft_*'
	add_all_modules '/netfilter/nf_tables*'
	add_file /etc/nftables.conf
	add_file /etc/nftables/public_ip.nft
	add_binary /usr/bin/nft
}

help() {
	cat <<EOF
Sets up nftables as a firewall
EOF
}

# vim: ai ts=4 sw=4 ft=sh:
