#!/usr/bin/ash

build() {
	add_runscript
	add_module dummy
	add_module e1000
	add_module igb
	add_binary /usr/bin/ip
	add_binary /usr/bin/dhcpcd
	add_binary /usr/bin/sysctl
}

help() {
	cat <<EOF
Identifies NICs for WAN and LAN and renames them to `wan` and `lan`
EOF
}

# vim: ai ts=4 sw=4 ft=sh:
