name: Test Charch Build

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y cpio zstd xorriso syslinux syslinux-common isolinux

      - name: Build
        run: scripts/build.sh --use-cache --skip-iso
