name: Tesh Charch Build

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: scripts/build.sh
