name: Root Hints

on:
  schedule:
  - cron: "15 0,5,11,17 * * *"

jobs:
  mirrors:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get root hints
      run: |
        curl -fsSL https://www.internic.net/domain/named.root > configs/etc/unbound/root.hints

    - name: Commit Mirrors
      run: |
        git config --local user.email "jacob@mcswain.dev"
        git config --local user.name "Jacob McSwain"
        git add configs/etc/unbound/root.hints
        git commit --signoff -m "Update Root Hints"
        git push
